services:
  app:
    build: .
    command: 'uvicorn main:app --reload --host 0.0.0.0'
    ports:
      - '8000:8000'
    networks:
      - rede_docker
    volumes: 
      - ./:/app

networks:
  rede_docker:
    external: true
